project:
  type: website

website:
  title: "Precision Environmental Health with Mixture Exposures"
  description: "A website for products from the Precision Environmental Health with Mixture Exposures project."
  navbar:
    right:
      - icon: github
        href: https://github.com/PrecisionEnvironmentalHealth/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



