---
title: "Distributed Lag Interaction Model with Index Modification"
date: 05/05/2025
categories: 
  - Stat Methods Paper
  - Software
---



**Abstract:** Epidemiological evidence supports an association between exposure to air pollution during pregnancy and birth and child health outcomes. Typically, such associations are estimated by regressing an outcome on daily or weekly measures of exposure during pregnancy using a distributed lag model. However, these associations may be modified by multiple factors.  We propose a distributed lag interaction model with index modification that allows for effect modification of a functional predictor by a weighted average of multiple modifiers. Our model allows for simultaneous estimation of modifier index weights and the exposure-time-response function via a spline cross-basis in a Bayesian hierarchical framework. Through simulations, we showed that our model out-performs competing methods when there are multiple modifiers of unknown importance. We applied our proposed method to a Colorado birth cohort to estimate the association between birth weight and air pollution modified by a neighborhood-vulnerability index and to a Mexican birth cohort to estimate the association between birthing-parent cardio-metabolic endpoints and air pollution modified by a birthing-parent lifetime stress index.


**Citation:** Danielle Demateis, Sandra India Aldana, Robert O. Wright, Rosalind Wright, Andrea Baccarelli, Elena Colicino, Ander Wilson, Kayleigh P. Keller (In press). Distributed Lag Interaction Model with Index Modification. _Biostatistics_. [arXiv:2504.06363 ](https://arxiv.org/abs/2504.06363)


**Software and data sharing:** This paper uses the R package `dlimIM` v0.1.0 ([DOI:10.5281/zenodo.15354392](https://doi.org/10.5281/zenodo.15354392)). Code to reproduce the data analyses and simulations and information of data access is available at [https://github.com/ddemateis/dlimIM_simulations](https://github.com/ddemateis/dlimIM_simulations) ([DOI:10.5281/zenodo.15361933](https://doi.org/10.5281/zenodo.15361933)).

