---
title: "Structured Bayesian Regression Tree Models for Estimating Distributed Lag Effects: The R Package dlmtree"
date: 05/08/2025
categories: 
  - Software Paper
  - R Package on CRAN
  - Software
---

**Abstract:** When examining the relationship between an exposure and an outcome, there is often a time lag between exposure and the observed effect on the outcome. A common statistical approach for estimating the relationship between the outcome and lagged measurements of exposure is a distributed lag model (DLM). Because repeated measurements are often autocorrelated, the lagged effects are typically constrained to vary smoothly over time. A recent statistical development on the smoothing constraint is a tree structured DLM framework. We present an R package dlmtree, available on CRAN, that integrates tree structured DLM and extensions into a comprehensive software package with user-friendly implementation. A conceptual background on tree structured DLMs and demonstration of the fitting process of each model using simulated data are provided. We also demonstrate inference and interpretation using the fitted models, including summary and visualization. Additionally, a built-in shiny app for heterogeneity analysis is included.

**Citation:** Seongwon Im, Daniel Mork, Ander Wilson (In press). Structured Bayesian Regression Tree Models for Estimating Distributed Lag Effects: The R Package dlmtree. _The R Journal_. [arXiv:2504.18452 ](https://arxiv.org/abs/2504.18452). [DOI:10.32614/RJ-2025-007](https://doi.org/10.32614/RJ-2025-007).

**Software and data sharing:** All software is included in the paper and supplement. There is no data used in this package. This accompanies the R package `dlmtree` ([https://danielmork.github.io/dlmtree/](https://github.com/danielmork/dlmtree), [DOI: 10.32614/CRAN.package.dlmtree](http://doi.org/10.32614/CRAN.package.dlmtree)). The supplement is available at [https://github.com/PrecisionEnvironmentalHealth/dlmtree_paper_supplement_code](https://github.com/PrecisionEnvironmentalHealth/dlmtree_paper_supplement_code).
